name: toktik
description: A new Flutter project.
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=3.1.0 <4.0.0'

dependencies:
  animate_do: ^3.3.4
  cupertino_icons: ^1.0.2
  flutter:
    sdk: flutter
  intl: ^0.19.0
  provider: ^6.1.2
  video_player: ^2.8.3

dev_dependencies:
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter

flutter:

  uses-material-design: true

  assets:
    - assets/videos/
